# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN= "e33b7db1-ce1c-4d0f-aec8-27e177a257c9"
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - postgresql

before_install:
  - psql -c 'create database grabber;' -U postgres

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -griganuragan@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


